tecnologies = {'JavaScript': 0,
                   'CSS': 0,
                   'React Native': 0,
                   'Node.js': 0,
                   'ReactJS': 0,
                   'PHP': 0,
                   'HTML': 0,
                   'Angular': 0,
                   'Vue.js': 0,
                   'Laravel': 0,
                   'MySQL': 0,
                   'Ionic': 0,
                   '.NET': 0,
                   'SQL Server': 0,
                   'AWS RDS (Relational Database Service)': 0,
                   'AWS S3': 0,
                   'C#': 0,
                   'MongoDB': 0}